# Generated by Django 3.2.13 on 2022-05-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220528_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tank',
            new_name='tags',
        ),
    ]
